name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
    paths:
      - '**.go'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version-file: 'go.mod'
      - name: Build UI
        run: make ui
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: 'latest'
